---
:machine:
  # https://app.vagrantup.com/bento/boxes/ubuntu-20-04
  :box: bento/ubuntu-20.04 # 64GB HDD
  :memory: 8072 # 8GB RAM
  :cpus: 4
  :hostname: ubuntu-20-04-icc
  :timezone: Canada/Pacific

:forwarded_ports:
# SSH
- :id: ssh
  :host: 2222
  :guest: 22
# HTTP
- :host: 80
  :guest: 80
# dB
- :host: 33060
  :guest: 3306

:synced_folder:
  :host: C:/Sites/
  :guest: /home/vagrant/Sites

:copy_files:
- :source: C:/VM/ubuntu-20-04-icc/backup/dbs
  :destination: /home/vagrant/dbs


:php_error_reporting: E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT
...
